import { CarsDataType, Country } from '../types/catalog'

export const countries: Country[] = [
    { id: 'china', name: 'Китай' },
    { id: 'japan', name: 'Япония' },
    { id: 'korea', name: 'Корея' },
    { id: 'europe', name: 'Европа' },
]

export const categories = [
    'Все',
    'Кроссоверы',
    'Седаны',
    'Электромобили',
    'Минивэны',
]

export const priceRanges = [
    'Все цены',
    'До 2 млн',
    '2-3 млн',
    '3-4 млн',
    'От 4 млн',
]

export const carsData: CarsDataType = {
    china: [
        {
            id: '1',
            brand: 'BYD',
            model: 'Han',
            year: 2023,
            category: 'Кроссоверы',
            price: 2355000,
            images: [
                '/img/catalog/china/BYD-Han/1.jpg',
                '/img/catalog/china/BYD-Han/2.jpg',
                '/img/catalog/china/BYD-Han/3.jpg',
                '/img/catalog/china/BYD-Han/4.jpg',
                '/img/catalog/china/BYD-Han/5.jpg',
                '/img/catalog/china/BYD-Han/6.jpg',
                '/img/catalog/china/BYD-Han/7.jpg',
                '/img/catalog/china/BYD-Han/8.jpg',
                '/img/catalog/china/BYD-Han/9.jpg',
                '/img/catalog/china/BYD-Han/10.jpg',
                '/img/catalog/china/BYD-Han/11.jpg',
                '/img/catalog/china/BYD-Han/12.jpg',
                '/img/catalog/china/BYD-Han/13.jpg',
                '/img/catalog/china/BYD-Han/14.jpg',
                '/img/catalog/china/BYD-Han/15.jpg',
                '/img/catalog/china/BYD-Han/16.jpg',
                '/img/catalog/china/BYD-Han/17.jpg',
                '/img/catalog/china/BYD-Han/18.jpg',
                '/img/catalog/china/BYD-Han/19.jpg',
                '/img/catalog/china/BYD-Han/20.jpg',
                '/img/catalog/china/BYD-Han/21.jpg',
                '/img/catalog/china/BYD-Han/22.jpg',
                '/img/catalog/china/BYD-Han/23.jpg',
                '/img/catalog/china/BYD-Han/24.jpg',
                '/img/catalog/china/BYD-Han/25.jpg',
            ],
            specs: {
                mileage: 22000,
                engineVolume: 2.0,
                fuelType: 'Hybrid',
                horsePower: 192,
                transmission: 'Робот',
                driveType: 'Полный',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '2',
            brand: 'BYD',
            model: 'Song-Plus DM-I',
            year: 2021,
            category: 'Кроссоверы',
            price: 1888000,
            equipment: 'Пред Максимальная комплектация',
            images: [
                '/img/catalog/china/BYD-Song-Plus/1.jpg',
                '/img/catalog/china/BYD-Song-Plus/2.jpg',
                '/img/catalog/china/BYD-Song-Plus/3.jpg',
                '/img/catalog/china/BYD-Song-Plus/4.jpg',
            ],
            specs: {
                mileage: 23000,
                engineVolume: 1.5,
                fuelType: 'Hybrid',
                horsePower: 110,
                transmission: 'Вариатор',
                driveType: 'Передний ',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '3',
            brand: 'CHANGAN',
            model: 'Uni-K',
            year: 2021,
            category: 'Кроссоверы',
            price: 2495000,
            images: [
                '/img/catalog/china/CHANGAN-Uni-K/19.jpg',
                '/img/catalog/china/CHANGAN-Uni-K/18.jpg',
                '/img/catalog/china/CHANGAN-Uni-K/13.jpg',
                '/img/catalog/china/CHANGAN-Uni-K/14.jpg',
                '/img/catalog/china/CHANGAN-Uni-K/15.jpg',
                '/img/catalog/china/CHANGAN-Uni-K/10.jpg',
                '/img/catalog/china/CHANGAN-Uni-K/11.jpg',
                '/img/catalog/china/CHANGAN-Uni-K/12.jpg',
                '/img/catalog/china/CHANGAN-Uni-K/16.jpg',
                '/img/catalog/china/CHANGAN-Uni-K/20.jpg',
            ],
            specs: {
                mileage: 39000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 233,
                transmission: 'Автомат',
                driveType: 'Передний',
                features: [
                    'Камеры 360',
                    'Панорамный люк',
                    'Подогрев и обдув сидений',
                    'Память и обогрев зеркал',
                ],
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '4',
            brand: 'Chery',
            model: 'Arrizo8',
            year: 2021,
            category: 'Седаны',
            price: 2165000,
            images: [
                '/img/catalog/china/Chery-Arrizo8/1.jpg',
                '/img/catalog/china/Chery-Arrizo8/2.jpg',
                '/img/catalog/china/Chery-Arrizo8/3.jpg',
                '/img/catalog/china/Chery-Arrizo8/4.jpg',
                '/img/catalog/china/Chery-Arrizo8/5.jpg',
                '/img/catalog/china/Chery-Arrizo8/6.jpg',
                '/img/catalog/china/Chery-Arrizo8/7.jpg',
                '/img/catalog/china/Chery-Arrizo8/8.jpg',
                '/img/catalog/china/Chery-Arrizo8/9.jpg',
            ],
            specs: {
                mileage: 18000,
                engineVolume: 1.6,
                fuelType: 'Бензин',
                horsePower: 197,
                transmission: 'Робот',
                driveType: 'Передний',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '5',
            brand: 'Geely',
            model: 'Coolray',
            year: 2021,
            category: 'Кроссоверы',
            price: 1413000,
            images: [
                '/img/catalog/china/Geely-Coolray/1.jpg',
                '/img/catalog/china/Geely-Coolray/2.jpg',
                '/img/catalog/china/Geely-Coolray/3.jpg',
                '/img/catalog/china/Geely-Coolray/4.jpg',
                '/img/catalog/china/Geely-Coolray/5.jpg',
                '/img/catalog/china/Geely-Coolray/6.jpg',
                '/img/catalog/china/Geely-Coolray/7.jpg',
                '/img/catalog/china/Geely-Coolray/8.jpg',
                '/img/catalog/china/Geely-Coolray/9.jpg',
            ],
            specs: {
                mileage: 0,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 177,
                transmission: 'Робот',
                driveType: 'Передний',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '6',
            brand: 'Geely',
            model: 'Emgrand',
            year: 2021,
            category: 'Седаны',
            price: 1172500,
            images: [
                '/img/catalog/china/Geely-Emgrand/1.jpg',
                '/img/catalog/china/Geely-Emgrand/2.jpg',
                '/img/catalog/china/Geely-Emgrand/3.jpg',
                '/img/catalog/china/Geely-Emgrand/4.jpg',
                '/img/catalog/china/Geely-Emgrand/5.jpg',
                '/img/catalog/china/Geely-Emgrand/6.jpg',
                '/img/catalog/china/Geely-Emgrand/7.jpg',
                '/img/catalog/china/Geely-Emgrand/8.jpg',
                '/img/catalog/china/Geely-Emgrand/9.jpg',
                '/img/catalog/china/Geely-Emgrand/10.jpg',
            ],
            specs: {
                mileage: 25000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 114,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '7',
            brand: 'Haval',
            model: 'Dargo',
            year: 2021,
            category: 'Кроссоверы',
            price: 2257000,
            images: [
                '/img/catalog/china/Haval-Dargo/1.jpg',
                '/img/catalog/china/Haval-Dargo/2.jpg',
                '/img/catalog/china/Haval-Dargo/3.jpg',
                '/img/catalog/china/Haval-Dargo/4.jpg',
                '/img/catalog/china/Haval-Dargo/5.jpg',
                '/img/catalog/china/Haval-Dargo/6.jpg',
                '/img/catalog/china/Haval-Dargo/7.jpg',
                '/img/catalog/china/Haval-Dargo/8.jpg',
                '/img/catalog/china/Haval-Dargo/9.jpg',
                '/img/catalog/china/Haval-Dargo/10.jpg',
            ],
            specs: {
                mileage: 40000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 211,
                transmission: 'Робот',
                driveType: '4WD',
                features: ['Максимальная комплектация'],
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '8',
            brand: 'Haval',
            model: 'Dargo',
            year: 2021,
            category: 'Кроссоверы',
            price: 1914000,
            images: [
                '/img/catalog/china/Haval-Dargo_Avial/1.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/2.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/3.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/4.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/5.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/6.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/7.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/8.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/9.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/10.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/11.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/12.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/13.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/14.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/15.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/16.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/17.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/18.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/19.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/20.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/21.jpg',
                '/img/catalog/china/Haval-Dargo_Avial/22.jpg',
            ],
            specs: {
                mileage: 39000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 169,
                transmission: 'Робот',
                driveType: 'Передний',
                features: [
                    'Камеры 360',
                    'Круиз-контроль',
                    'Панорамный люк',
                    'Подогрев руля',
                    'Подогрев и обдув сидений',
                    'Обогрев зеркал',
                ],
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '9',
            brand: 'Haval',
            model: 'M6 Plus',
            year: 2024,
            category: 'Кроссоверы',
            price: 1690000,
            images: [
                '/img/catalog/china/Haval-M6-mkpp/1.webp',
                '/img/catalog/china/Haval-M6-mkpp/2.webp',
                '/img/catalog/china/Haval-M6-mkpp/3.webp',
                '/img/catalog/china/Haval-M6-mkpp/11.webp',
                '/img/catalog/china/Haval-M6-mkpp/12.webp',
                '/img/catalog/china/Haval-M6-mkpp/13.webp',
            ],
            specs: {
                mileage: 0,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 0,
                transmission: 'Механика',
                driveType: 'Передний',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '10',
            brand: 'Haval',
            model: 'M6 Plus',
            year: 2024,
            category: 'Кроссоверы',
            price: 1980000,
            images: [
                '/img/catalog/china/Haval-M6-robot/6.webp',
                '/img/catalog/china/Haval-M6-robot/7.webp',
                '/img/catalog/china/Haval-M6-robot/8.webp',
                '/img/catalog/china/Haval-M6-robot/9.webp',
                '/img/catalog/china/Haval-M6-robot/10.webp',
                '/img/catalog/china/Haval-M6-robot/11.webp',
                '/img/catalog/china/Haval-M6-robot/12.webp',
                '/img/catalog/china/Haval-M6-robot/13.webp',
                '/img/catalog/china/Haval-M6-robot/14.webp',
                '/img/catalog/china/Haval-M6-robot/5.webp',
                '/img/catalog/china/Haval-M6-robot/4.webp',
                '/img/catalog/china/Haval-M6-robot/3.webp',
                '/img/catalog/china/Haval-M6-robot/2.webp',
                '/img/catalog/china/Haval-M6-robot/1.webp',
            ],
            specs: {
                mileage: 30000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 150,
                transmission: 'Робот',
                driveType: 'Передний',
                features: ['Максимальная комплектация'],
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '11',
            brand: 'Oshan',
            model: 'X5',
            year: 2024,
            category: 'Кроссоверы',
            price: 1350000,
            images: [
                '/img/catalog/china/Oshan-X5/1.jpg',
                '/img/catalog/china/Oshan-X5/2.jpg',
                '/img/catalog/china/Oshan-X5/3.jpg',
                '/img/catalog/china/Oshan-X5/4.jpg',
                '/img/catalog/china/Oshan-X5/5.jpg',
                '/img/catalog/china/Oshan-X5/6.jpg',
                '/img/catalog/china/Oshan-X5/7.jpg',
                '/img/catalog/china/Oshan-X5/8.jpg',
                '/img/catalog/china/Oshan-X5/9.jpg',
                '/img/catalog/china/Oshan-X5/10.jpg',
                '/img/catalog/china/Oshan-X5/11.jpg',
                '/img/catalog/china/Oshan-X5/12.jpg',
                '/img/catalog/china/Oshan-X5/13.jpg',
                '/img/catalog/china/Oshan-X5/14.jpg',
                '/img/catalog/china/Oshan-X5/15.jpg',
                '/img/catalog/china/Oshan-X5/16.jpg',
                '/img/catalog/china/Oshan-X5/17.jpg',
                '/img/catalog/china/Oshan-X5/18.jpg',
                '/img/catalog/china/Oshan-X5/19.jpg',
                '/img/catalog/china/Oshan-X5/20.jpg',
            ],
            specs: {
                mileage: 23000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 180,
                transmission: 'Робот',
                driveType: 'Передний',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '12',
            brand: 'Changan',
            model: 'CS75PLUS',
            year: 2022,
            category: 'Кроссоверы',
            price: 1715000,
            images: [
                '/img/catalog/china/drom/Changan-CS75Plus/1.jpg',
                '/img/catalog/china/drom/Changan-CS75Plus/2.jpg',
                '/img/catalog/china/drom/Changan-CS75Plus/3.jpg',
                '/img/catalog/china/drom/Changan-CS75Plus/4.jpg',
                '/img/catalog/china/drom/Changan-CS75Plus/5.jpg',
                '/img/catalog/china/drom/Changan-CS75Plus/6.jpg',
                '/img/catalog/china/drom/Changan-CS75Plus/7.jpg',
                '/img/catalog/china/drom/Changan-CS75Plus/8.jpg',
                '/img/catalog/china/drom/Changan-CS75Plus/9.jpg',
                '/img/catalog/china/drom/Changan-CS75Plus/10.jpg',
                '/img/catalog/china/drom/Changan-CS75Plus/11.jpg',
            ],
            specs: {
                mileage: 19000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 188,
                transmission: 'АКПП',
                driveType: 'Передний',
                color: 'Белый',
                generation: '2 поколение',
                features: ['1.5 AT Exclusive'],
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '13',
            brand: 'GAC',
            model: 'M6 Trumpchi',
            year: 2021,
            category: 'Минивэны',
            price: 1750000,
            images: [
                '/img/catalog/china/drom/Gac-M6/1.jpg',
                '/img/catalog/china/drom/Gac-M6/2.jpg',
                '/img/catalog/china/drom/Gac-M6/3.jpg',
                '/img/catalog/china/drom/Gac-M6/14.jpg',
                '/img/catalog/china/drom/Gac-M6/15.jpg',
                '/img/catalog/china/drom/Gac-M6/16.jpg',
                '/img/catalog/china/drom/Gac-M6/17.jpg',
                '/img/catalog/china/drom/Gac-M6/4.jpg',
                '/img/catalog/china/drom/Gac-M6/5.jpg',
                '/img/catalog/china/drom/Gac-M6/6.jpg',
                '/img/catalog/china/drom/Gac-M6/7.jpg',
                '/img/catalog/china/drom/Gac-M6/8.jpg',
                '/img/catalog/china/drom/Gac-M6/9.jpg',
                '/img/catalog/china/drom/Gac-M6/10.jpg',
                '/img/catalog/china/drom/Gac-M6/11.jpg',
                '/img/catalog/china/drom/Gac-M6/12.jpg',
                '/img/catalog/china/drom/Gac-M6/13.jpg',
            ],
            specs: {
                mileage: 28000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 169,
                transmission: 'Робот',
                driveType: 'Передний',
                color: 'Белый',
                generation: '1 поколение',
                features: ['1.5T DCT 2WD 270T Premium Edition 6 seats'],
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '14',
            brand: 'Exeed',
            model: 'LX',
            year: 2022,
            category: 'Кроссоверы',
            price: 1900000,
            images: [
                '/img/catalog/china/drom/Exeed-LX/1.jpg',
                '/img/catalog/china/drom/Exeed-LX/2.jpg',
                '/img/catalog/china/drom/Exeed-LX/3.jpg',
                '/img/catalog/china/drom/Exeed-LX/4.jpg',
                '/img/catalog/china/drom/Exeed-LX/5.jpg',
                '/img/catalog/china/drom/Exeed-LX/6.jpg',
                '/img/catalog/china/drom/Exeed-LX/7.jpg',
                '/img/catalog/china/drom/Exeed-LX/8.jpg',
                '/img/catalog/china/drom/Exeed-LX/9.jpg',
                '/img/catalog/china/drom/Exeed-LX/10.jpg',
                '/img/catalog/china/drom/Exeed-LX/11.jpg',
            ],
            specs: {
                mileage: 15000,
                engineVolume: 1.6,
                fuelType: 'Бензин',
                horsePower: 197,
                transmission: 'Робот',
                driveType: 'Передний',
                color: 'Черный',
                generation: '1 поколение, рестайлинг',
                features: ['Zhuifeng 1.6T DCT Goddess 300T'],
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '15',
            brand: 'Geely',
            model: 'Mongaro',
            year: 2021,
            category: 'Кроссоверы',
            price: 2800000,
            images: [
                '/img/catalog/china/drom/Gelly-Mongaro/1.jpg',
                '/img/catalog/china/drom/Gelly-Mongaro/2.jpg',
                '/img/catalog/china/drom/Gelly-Mongaro/13.jpg',
                '/img/catalog/china/drom/Gelly-Mongaro/3.jpg',
                '/img/catalog/china/drom/Gelly-Mongaro/4.jpg',
                '/img/catalog/china/drom/Gelly-Mongaro/5.jpg',
                '/img/catalog/china/drom/Gelly-Mongaro/6.jpg',
                '/img/catalog/china/drom/Gelly-Mongaro/7.jpg',
                '/img/catalog/china/drom/Gelly-Mongaro/8.jpg',
                '/img/catalog/china/drom/Gelly-Mongaro/9.jpg',
                '/img/catalog/china/drom/Gelly-Mongaro/10.jpg',
                '/img/catalog/china/drom/Gelly-Mongaro/11.jpg',
                '/img/catalog/china/drom/Gelly-Mongaro/12.jpg',
            ],
            specs: {
                mileage: 44000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 235,
                transmission: 'АКПП',
                driveType: '4WD',
                color: 'Черный',
                generation: '1 поколение',
                features: ['Xingyue L 2.0 AT Distinguished'],
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '16',
            brand: 'Geely',
            model: 'Tugella',
            year: 2021,
            category: 'Кроссоверы',
            price: 1950000,
            images: [
                '/img/catalog/china/drom/Gelly-Tugella/1.jpg',
                '/img/catalog/china/drom/Gelly-Tugella/2.jpg',
                '/img/catalog/china/drom/Gelly-Tugella/3.jpg',
                '/img/catalog/china/drom/Gelly-Tugella/4.jpg',
                '/img/catalog/china/drom/Gelly-Tugella/5.jpg',
                '/img/catalog/china/drom/Gelly-Tugella/6.jpg',
                '/img/catalog/china/drom/Gelly-Tugella/16.jpg',
                '/img/catalog/china/drom/Gelly-Tugella/7.jpg',
                '/img/catalog/china/drom/Gelly-Tugella/8.jpg',
                '/img/catalog/china/drom/Gelly-Tugella/9.jpg',
                '/img/catalog/china/drom/Gelly-Tugella/10.jpg',
                '/img/catalog/china/drom/Gelly-Tugella/11.jpg',
                '/img/catalog/china/drom/Gelly-Tugella/12.jpg',
                '/img/catalog/china/drom/Gelly-Tugella/13.jpg',
                '/img/catalog/china/drom/Gelly-Tugella/14.jpg',
                '/img/catalog/china/drom/Gelly-Tugella/15.jpg',
            ],
            specs: {
                mileage: 17000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 188,
                transmission: 'Робот',
                driveType: 'Передний',
                color: 'Серый',
                generation: '1 поколение, рестайлинг',
                features: ['Xingyue S 2.0 DCT Lightning'],
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '17',
            brand: 'TANK',
            model: '300',
            year: 2021,
            category: 'Внедорожники',
            price: 3020000,
            images: [
                '/img/catalog/china/drom/TANK-300/1.jpg',
                '/img/catalog/china/drom/TANK-300/2.jpg',
                '/img/catalog/china/drom/TANK-300/3.jpg',
                '/img/catalog/china/drom/TANK-300/8.jpg',
                '/img/catalog/china/drom/TANK-300/9.jpg',
                '/img/catalog/china/drom/TANK-300/10.jpg',
                '/img/catalog/china/drom/TANK-300/7.jpg',
                '/img/catalog/china/drom/TANK-300/2.jpg',
                '/img/catalog/china/drom/TANK-300/4.jpg',
                '/img/catalog/china/drom/TANK-300/5.jpg',
                '/img/catalog/china/drom/TANK-300/6.jpg',
            ],
            specs: {
                mileage: 23000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 227,
                transmission: 'АКПП',
                driveType: '4WD',
                color: 'Белый',
                generation: '1 поколение',
                features: ['2.0T AT 4WD Off-Road Conqueror'],
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '18',
            brand: 'Changan',
            model: 'Uni-T',
            year: 2021,
            category: 'Кроссоверы',
            price: 1580000,
            images: [
                '/img/catalog/china/drom/Unit-T-drom/1.jpg',
                '/img/catalog/china/drom/Unit-T-drom/2.jpg',
                '/img/catalog/china/drom/Unit-T-drom/3.jpg',
                '/img/catalog/china/drom/Unit-T-drom/4.jpg',
                '/img/catalog/china/drom/Unit-T-drom/5.jpg',
                '/img/catalog/china/drom/Unit-T-drom/6.jpg',
                '/img/catalog/china/drom/Unit-T-drom/7.jpg',
                '/img/catalog/china/drom/Unit-T-drom/8.jpg',
                '/img/catalog/china/drom/Unit-T-drom/9.jpg',
                '/img/catalog/china/drom/Unit-T-drom/10.jpg',
                '/img/catalog/china/drom/Unit-T-drom/11.jpg',
                '/img/catalog/china/drom/Unit-T-drom/12.jpg',
                '/img/catalog/china/drom/Unit-T-drom/13.jpg',
                '/img/catalog/china/drom/Unit-T-drom/14.jpg',
                '/img/catalog/china/drom/Unit-T-drom/15.jpg',
            ],
            specs: {
                mileage: 22000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 180,
                transmission: 'Робот',
                driveType: 'Передний',
                color: 'Серый',
                generation: '1 поколение',
                features: ['1.5 AMT'],
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '19',
            brand: 'Changan',
            model: 'Uni-K',
            year: 2021,
            category: 'Кроссоверы',
            price: 2399000,
            images: [
                '/img/catalog/china/drom/Uni-K-drom/1.jpg',
                '/img/catalog/china/drom/Uni-K-drom/2.jpg',
                '/img/catalog/china/drom/Uni-K-drom/3.jpg',
                '/img/catalog/china/drom/Uni-K-drom/4.jpg',
                '/img/catalog/china/drom/Uni-K-drom/5.jpg',
                '/img/catalog/china/drom/Uni-K-drom/6.jpg',
                '/img/catalog/china/drom/Uni-K-drom/7.jpg',
                '/img/catalog/china/drom/Uni-K-drom/8.jpg',
                '/img/catalog/china/drom/Uni-K-drom/9.jpg',
                '/img/catalog/china/drom/Uni-K-drom/10.jpg',
                '/img/catalog/china/drom/Uni-K-drom/11.jpg',
                '/img/catalog/china/drom/Uni-K-drom/12.jpg',
                '/img/catalog/china/drom/Uni-K-drom/13.jpg',
            ],
            specs: {
                mileage: 28000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 233,
                transmission: 'АКПП',
                driveType: '4WD',
                color: 'Голубой',
                generation: '1 поколение',
                features: ['2.0 AT Premium'],
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
    ],
    japan: [
        {
            id: '26',
            brand: 'Toyota',
            model: 'Corolla Cross',
            year: 2022,
            category: 'Кроссоверы',
            price: 1690000,
            images: [
                '/img/catalog/jp/Corolla-Cross/1.jpg',
                '/img/catalog/jp/Corolla-Cross/2.jpg',
                '/img/catalog/jp/Corolla-Cross/3.jpg',
                '/img/catalog/jp/Corolla-Cross/4.jpg',
                '/img/catalog/jp/Corolla-Cross/5.jpg',
                '/img/catalog/jp/Corolla-Cross/6.jpg',
                '/img/catalog/jp/Corolla-Cross/7.jpg',
                '/img/catalog/jp/Corolla-Cross/8.jpg',
                '/img/catalog/jp/Corolla-Cross/9.jpg',
                '/img/catalog/jp/Corolla-Cross/10.jpg',
                '/img/catalog/jp/Corolla-Cross/11.jpg',
                '/img/catalog/jp/Corolla-Cross/12.jpg',
                '/img/catalog/jp/Corolla-Cross/13.jpg',
                '/img/catalog/jp/Corolla-Cross/14.jpg',
                '/img/catalog/jp/Corolla-Cross/15.jpg',
                '/img/catalog/jp/Corolla-Cross/16.jpg',
                '/img/catalog/jp/Corolla-Cross/17.jpg',
                '/img/catalog/jp/Corolla-Cross/18.jpg',
                '/img/catalog/jp/Corolla-Cross/19.jpg',
                '/img/catalog/jp/Corolla-Cross/20.jpg',
            ],
            specs: {
                mileage: 5000,
                engineVolume: 2.0,
                fuelType: 'Гибрид',
                horsePower: 152,
                transmission: 'Вариатор (CVT)',
                driveType: 'Передний',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '27',
            brand: 'Eclipse',
            model: 'Cross',
            year: 2020,
            category: 'Кроссоверы',
            price: 1690000,
            images: [
                '/img/catalog/jp/Eclips-Cross/1.jpg',
                '/img/catalog/jp/Eclips-Cross/2.jpg',
                '/img/catalog/jp/Eclips-Cross/3.jpg',
                '/img/catalog/jp/Eclips-Cross/4.jpg',
                '/img/catalog/jp/Eclips-Cross/5.jpg',
                '/img/catalog/jp/Eclips-Cross/6.jpg',
                '/img/catalog/jp/Eclips-Cross/7.jpg',
            ],
            specs: {
                mileage: 35000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 170,
                transmission: 'Вариатор',
                driveType: '4WD',
                color: 'Серый',
                generation: '1 поколение',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '28',
            brand: 'Toyota',
            model: 'Harrier',
            year: 2021,
            category: 'Кроссоверы',
            price: 3802800,
            images: [
                '/img/catalog/jp/Harrier/1.jpg',
                '/img/catalog/jp/Harrier/2.jpg',
                '/img/catalog/jp/Harrier/3.jpg',
                '/img/catalog/jp/Harrier/4.jpg',
                '/img/catalog/jp/Harrier/5.jpg',
            ],
            specs: {
                mileage: 15000,
                engineVolume: 2.5,
                fuelType: 'Гибрид',
                horsePower: 178,
                transmission: 'Вариатор (CVT)',
                driveType: '4WD',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '29',
            brand: 'Honda',
            model: 'Breeze',
            year: 2021,
            category: 'Кроссоверы',
            price: 2400000,
            images: [
                '/img/catalog/jp/Honda-breeze/1.jpg',
                '/img/catalog/jp/Honda-breeze/2.jpg',
                '/img/catalog/jp/Honda-breeze/3.jpg',
                '/img/catalog/jp/Honda-breeze/4.jpg',
                '/img/catalog/jp/Honda-breeze/5.jpg',
                '/img/catalog/jp/Honda-breeze/6.jpg',
                '/img/catalog/jp/Honda-breeze/7.jpg',
                '/img/catalog/jp/Honda-breeze/8.jpg',
                '/img/catalog/jp/Honda-breeze/9.jpg',
                '/img/catalog/jp/Honda-breeze/10.jpg',
                '/img/catalog/jp/Honda-breeze/11.jpg',
                '/img/catalog/jp/Honda-breeze/12.jpg',
                '/img/catalog/jp/Honda-breeze/13.jpg',
                '/img/catalog/jp/Honda-breeze/14.jpg',
                '/img/catalog/jp/Honda-breeze/15.jpg',
                '/img/catalog/jp/Honda-breeze/16.jpg',
                '/img/catalog/jp/Honda-breeze/17.jpg',
                '/img/catalog/jp/Honda-breeze/18.jpg',
                '/img/catalog/jp/Honda-breeze/19.jpg',
                '/img/catalog/jp/Honda-breeze/20.jpg',
            ],
            specs: {
                mileage: 28000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 193,
                transmission: 'Вариатор',
                driveType: 'Передний',
                color: 'Белый',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '30',
            brand: 'Honda',
            model: 'Civic',
            year: 2021,
            category: 'Седаны',
            price: 1819500,
            images: [
                '/img/catalog/jp/Honda-Civic/1.jpg',
                '/img/catalog/jp/Honda-Civic/2.jpg',
                '/img/catalog/jp/Honda-Civic/3.jpg',
                '/img/catalog/jp/Honda-Civic/4.jpg',
                '/img/catalog/jp/Honda-Civic/5.jpg',
                '/img/catalog/jp/Honda-Civic/6.jpg',
                '/img/catalog/jp/Honda-Civic/7.jpg',
                '/img/catalog/jp/Honda-Civic/8.jpg',
                '/img/catalog/jp/Honda-Civic/9.jpg',
                '/img/catalog/jp/Honda-Civic/10.jpg',
                '/img/catalog/jp/Honda-Civic/11.jpg',
                '/img/catalog/jp/Honda-Civic/12.jpg',
                '/img/catalog/jp/Honda-Civic/13.jpg',
                '/img/catalog/jp/Honda-Civic/14.jpg',
                '/img/catalog/jp/Honda-Civic/15.jpg',
                '/img/catalog/jp/Honda-Civic/16.jpg',
                '/img/catalog/jp/Honda-Civic/17.jpg',
                '/img/catalog/jp/Honda-Civic/18.jpg',
                '/img/catalog/jp/Honda-Civic/19.jpg',
                '/img/catalog/jp/Honda-Civic/20.jpg',
                '/img/catalog/jp/Honda-Civic/21.jpg',
                '/img/catalog/jp/Honda-Civic/22.jpg',
                '/img/catalog/jp/Honda-Civic/23.jpg',
                '/img/catalog/jp/Honda-Civic/24.jpg',
                '/img/catalog/jp/Honda-Civic/25.jpg',
                '/img/catalog/jp/Honda-Civic/26.jpg',
            ],
            specs: {
                mileage: 42000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 182,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '31',
            brand: 'Honda',
            model: 'Civic Hatchback',
            year: 2021,
            category: 'Хэтчбеки',
            price: 1931000,
            images: [
                '/img/catalog/jp/Honda-Civic-HatchBack/1.jpg',
                '/img/catalog/jp/Honda-Civic-HatchBack/2.jpg',
                '/img/catalog/jp/Honda-Civic-HatchBack/3.jpg',
                '/img/catalog/jp/Honda-Civic-HatchBack/4.jpg',
                '/img/catalog/jp/Honda-Civic-HatchBack/5.jpg',
                '/img/catalog/jp/Honda-Civic-HatchBack/6.jpg',
                '/img/catalog/jp/Honda-Civic-HatchBack/7.jpg',
                '/img/catalog/jp/Honda-Civic-HatchBack/8.jpg',
                '/img/catalog/jp/Honda-Civic-HatchBack/9.jpg',
            ],
            specs: {
                mileage: 25000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 177,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '32',
            brand: 'Honda',
            model: 'CR-V',
            year: 2021,
            category: 'Кроссоверы',
            price: 2084000,
            images: [
                '/img/catalog/jp/Honda-CR-V/1.jpg',
                '/img/catalog/jp/Honda-CR-V/2.jpg',
                '/img/catalog/jp/Honda-CR-V/3.jpg',
                '/img/catalog/jp/Honda-CR-V/12.jpg',
                '/img/catalog/jp/Honda-CR-V/13.jpg',
                '/img/catalog/jp/Honda-CR-V/14.jpg',
                '/img/catalog/jp/Honda-CR-V/4.jpg',
                '/img/catalog/jp/Honda-CR-V/5.jpg',
                '/img/catalog/jp/Honda-CR-V/6.jpg',
                '/img/catalog/jp/Honda-CR-V/7.jpg',
                '/img/catalog/jp/Honda-CR-V/8.jpg',
                '/img/catalog/jp/Honda-CR-V/9.jpg',
                '/img/catalog/jp/Honda-CR-V/10.jpg',
                '/img/catalog/jp/Honda-CR-V/11.jpg',
            ],
            specs: {
                mileage: 33000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 193,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '33',
            brand: 'Honda',
            model: 'Fit',
            year: 2021,
            category: 'Субкомпактные',
            price: 1365000,
            images: [
                '/img/catalog/jp/Honda-Fit/1.jpg',
                '/img/catalog/jp/Honda-Fit/2.jpg',
                '/img/catalog/jp/Honda-Fit/3.jpg',
                '/img/catalog/jp/Honda-Fit/4.jpg',
                '/img/catalog/jp/Honda-Fit/5.jpg',
                '/img/catalog/jp/Honda-Fit/6.jpg',
                '/img/catalog/jp/Honda-Fit/7.jpg',
                '/img/catalog/jp/Honda-Fit/8.jpg',
                '/img/catalog/jp/Honda-Fit/9.jpg',
            ],
            specs: {
                mileage: 35000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 131,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '34',
            brand: 'Honda',
            model: 'Odyssey',
            year: 2021,
            category: 'Минивэны',
            price: 3290500,
            images: [
                '/img/catalog/jp/Honda-Odyssey/1.jpg',
                '/img/catalog/jp/Honda-Odyssey/2.jpg',
                '/img/catalog/jp/Honda-Odyssey/3.jpg',
                '/img/catalog/jp/Honda-Odyssey/10.jpg',
                '/img/catalog/jp/Honda-Odyssey/11.jpg',
                '/img/catalog/jp/Honda-Odyssey/12.jpg',
                '/img/catalog/jp/Honda-Odyssey/13.jpg',
                '/img/catalog/jp/Honda-Odyssey/7.jpg',
                '/img/catalog/jp/Honda-Odyssey/8.jpg',
                '/img/catalog/jp/Honda-Odyssey/9.jpg',
                '/img/catalog/jp/Honda-Odyssey/4.jpg',
                '/img/catalog/jp/Honda-Odyssey/5.jpg',
                '/img/catalog/jp/Honda-Odyssey/6.jpg',
                '/img/catalog/jp/Honda-Odyssey/14.jpg',
                '/img/catalog/jp/Honda-Odyssey/15.jpg',
                '/img/catalog/jp/Honda-Odyssey/16.jpg',
            ],
            specs: {
                mileage: 60000,
                engineVolume: 2.0,
                fuelType: 'Гибрид',
                horsePower: 146,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '35',
            brand: 'Honda',
            model: 'CR-V',
            year: 2021,
            category: 'Кроссоверы',
            price: 2200000,
            images: [
                '/img/catalog/jp/Honda-C-RV/1.jpg',
                '/img/catalog/jp/Honda-C-RV/2.jpg',
                '/img/catalog/jp/Honda-C-RV/3.jpg',
                '/img/catalog/jp/Honda-C-RV/4.jpg',
                '/img/catalog/jp/Honda-C-RV/5.jpg',
                '/img/catalog/jp/Honda-C-RV/6.jpg',
                '/img/catalog/jp/Honda-C-RV/7.jpg',
                '/img/catalog/jp/Honda-C-RV/8.jpg',
                '/img/catalog/jp/Honda-C-RV/9.jpg',
            ],
            specs: {
                mileage: 35000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 193,
                transmission: 'Вариатор',
                driveType: 'Передний',
                features: ['пред максимальная комплектация'],
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '36',
            brand: 'Honda',
            model: 'Fit',
            year: 2021,
            category: 'Субкомпактные',
            price: 1365000,
            images: [
                '/img/catalog/jp/Honda-Fit/1.jpg',
                '/img/catalog/jp/Honda-Fit/2.jpg',
                '/img/catalog/jp/Honda-Fit/3.jpg',
                '/img/catalog/jp/Honda-Fit/4.jpg',
                '/img/catalog/jp/Honda-Fit/5.jpg',
                '/img/catalog/jp/Honda-Fit/6.jpg',
                '/img/catalog/jp/Honda-Fit/7.jpg',
                '/img/catalog/jp/Honda-Fit/8.jpg',
                '/img/catalog/jp/Honda-Fit/9.jpg',
            ],
            specs: {
                mileage: 35000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 131,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '37',
            brand: 'Honda',
            model: 'Odyssey',
            year: 2021,
            category: 'Минивэны',
            price: 3290500,
            images: [
                '/img/catalog/jp/Honda-Odyssey/1.jpg',
                '/img/catalog/jp/Honda-Odyssey/2.jpg',
                '/img/catalog/jp/Honda-Odyssey/3.jpg',
                '/img/catalog/jp/Honda-Odyssey/10.jpg',
                '/img/catalog/jp/Honda-Odyssey/11.jpg',
                '/img/catalog/jp/Honda-Odyssey/12.jpg',
                '/img/catalog/jp/Honda-Odyssey/13.jpg',
                '/img/catalog/jp/Honda-Odyssey/7.jpg',
                '/img/catalog/jp/Honda-Odyssey/8.jpg',
                '/img/catalog/jp/Honda-Odyssey/9.jpg',
                '/img/catalog/jp/Honda-Odyssey/4.jpg',
                '/img/catalog/jp/Honda-Odyssey/5.jpg',
                '/img/catalog/jp/Honda-Odyssey/6.jpg',
                '/img/catalog/jp/Honda-Odyssey/14.jpg',
                '/img/catalog/jp/Honda-Odyssey/15.jpg',
                '/img/catalog/jp/Honda-Odyssey/16.jpg',
            ],
            specs: {
                mileage: 60000,
                engineVolume: 2.0,
                fuelType: 'Гибрид',
                horsePower: 146,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '38',
            brand: 'Honda',
            model: 'Accord',
            year: 2021,
            category: 'Седаны',
            price: 1950000,
            images: [
                '/img/catalog/jp/Hоnda-Accord/1.jpg',
                '/img/catalog/jp/Hоnda-Accord/2.jpg',
                '/img/catalog/jp/Hоnda-Accord/3.jpg',
                '/img/catalog/jp/Hоnda-Accord/4.jpg',
                '/img/catalog/jp/Hоnda-Accord/5.jpg',
                '/img/catalog/jp/Hоnda-Accord/6.jpg',
                '/img/catalog/jp/Hоnda-Accord/7.jpg',
                '/img/catalog/jp/Hоnda-Accord/8.jpg',
                '/img/catalog/jp/Hоnda-Accord/9.jpg',
            ],
            specs: {
                mileage: 30000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 194,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '39',
            brand: 'Nissan',
            model: 'Sylphy',
            year: 2021,
            category: 'Седаны',
            price: 1710500,
            images: [
                '/img/catalog/jp/Nissan-Sylphy/1.jpg',
                '/img/catalog/jp/Nissan-Sylphy/2.jpg',
                '/img/catalog/jp/Nissan-Sylphy/3.jpg',
                '/img/catalog/jp/Nissan-Sylphy/4.jpg',
                '/img/catalog/jp/Nissan-Sylphy/5.jpg',
                '/img/catalog/jp/Nissan-Sylphy/6.jpg',
                '/img/catalog/jp/Nissan-Sylphy/7.jpg',
                '/img/catalog/jp/Nissan-Sylphy/8.jpg',
                '/img/catalog/jp/Nissan-Sylphy/9.jpg',
                '/img/catalog/jp/Nissan-Sylphy/10.jpg',
                '/img/catalog/jp/Nissan-Sylphy/11.jpg',
                '/img/catalog/jp/Nissan-Sylphy/12.jpg',
            ],
            specs: {
                mileage: 30000,
                engineVolume: 1.6,
                fuelType: 'Бензин',
                horsePower: 135,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '40',
            brand: 'Nissan',
            model: 'X-Trail',
            year: 2021,
            category: 'Кроссоверы',
            price: 3100000,
            images: [
                '/img/catalog/jp/Nissan-X-Trail/1.jpg',
                '/img/catalog/jp/Nissan-X-Trail/2.jpg',
                '/img/catalog/jp/Nissan-X-Trail/3.jpg',
                '/img/catalog/jp/Nissan-X-Trail/7.jpg',
                '/img/catalog/jp/Nissan-X-Trail/9.jpg',
                '/img/catalog/jp/Nissan-X-Trail/10.jpg',
                '/img/catalog/jp/Nissan-X-Trail/11.jpg',
                '/img/catalog/jp/Nissan-X-Trail/12.jpg',
                '/img/catalog/jp/Nissan-X-Trail/13.jpg',
                '/img/catalog/jp/Nissan-X-Trail/8.jpg',
                '/img/catalog/jp/Nissan-X-Trail/4.jpg',
                '/img/catalog/jp/Nissan-X-Trail/5.jpg',
                '/img/catalog/jp/Nissan-X-Trail/6.jpg',
            ],
            specs: {
                mileage: 2000,
                engineVolume: 1.5,
                fuelType: 'Гибрид',
                horsePower: 144,
                transmission: 'АКПП',
                driveType: '4WD',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '41',
            brand: 'Subaru',
            model: 'Forester',
            year: 2021,
            category: 'Кроссоверы',
            price: 2575500,
            images: [
                '/img/catalog/jp/Subaru-Forester/1.jpg',
                '/img/catalog/jp/Subaru-Forester/2.jpg',
                '/img/catalog/jp/Subaru-Forester/3.jpg',
                '/img/catalog/jp/Subaru-Forester/7.jpg',
                '/img/catalog/jp/Subaru-Forester/8.jpg',
                '/img/catalog/jp/Subaru-Forester/9.jpg',
                '/img/catalog/jp/Subaru-Forester/4.jpg',
                '/img/catalog/jp/Subaru-Forester/5.jpg',
                '/img/catalog/jp/Subaru-Forester/6.jpg',
            ],
            specs: {
                mileage: 60000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 154,
                transmission: 'Вариатор',
                driveType: '4WD',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '42',
            brand: 'Toyota',
            model: 'Camry',
            year: 2021,
            category: 'Седаны',
            price: 2640000,
            images: [
                '/img/catalog/jp/Toyota-Camry/1.jpg',
                '/img/catalog/jp/Toyota-Camry/2.jpg',
                '/img/catalog/jp/Toyota-Camry/3.jpg',
                '/img/catalog/jp/Toyota-Camry/13.jpg',
                '/img/catalog/jp/Toyota-Camry/14.jpg',
                '/img/catalog/jp/Toyota-Camry/15.jpg',
                '/img/catalog/jp/Toyota-Camry/7.jpg',
                '/img/catalog/jp/Toyota-Camry/4.jpg',
                '/img/catalog/jp/Toyota-Camry/5.jpg',
                '/img/catalog/jp/Toyota-Camry/6.jpg',
                '/img/catalog/jp/Toyota-Camry/8.jpg',
                '/img/catalog/jp/Toyota-Camry/9.jpg',
                '/img/catalog/jp/Toyota-Camry/10.jpg',
                '/img/catalog/jp/Toyota-Camry/11.jpg',
                '/img/catalog/jp/Toyota-Camry/12.jpg',
            ],
            specs: {
                mileage: 32000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 178,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '43',
            brand: 'Toyota',
            model: 'CH-R',
            year: 2021,
            category: 'Кроссоверы',
            price: 2009000,
            images: [
                '/img/catalog/jp/Toyota-CH-R/1.jpg',
                '/img/catalog/jp/Toyota-CH-R/2.jpg',
                '/img/catalog/jp/Toyota-CH-R/10.jpg',
                '/img/catalog/jp/Toyota-CH-R/11.jpg',
                '/img/catalog/jp/Toyota-CH-R/12.jpg',
                '/img/catalog/jp/Toyota-CH-R/17.jpg',
                '/img/catalog/jp/Toyota-CH-R/18.jpg',
                '/img/catalog/jp/Toyota-CH-R/7.jpg',
                '/img/catalog/jp/Toyota-CH-R/6.jpg',
                '/img/catalog/jp/Toyota-CH-R/3.jpg',
                '/img/catalog/jp/Toyota-CH-R/4.jpg',
                '/img/catalog/jp/Toyota-CH-R/5.jpg',
                '/img/catalog/jp/Toyota-CH-R/8.jpg',
                '/img/catalog/jp/Toyota-CH-R/9.jpg',
                '/img/catalog/jp/Toyota-CH-R/13.jpg',
                '/img/catalog/jp/Toyota-CH-R/14.jpg',
                '/img/catalog/jp/Toyota-CH-R/15.jpg',
                '/img/catalog/jp/Toyota-CH-R/16.jpg',
            ],
            specs: {
                mileage: 42000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 171,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '44',
            brand: 'Toyota',
            model: 'Harrier',
            year: 2021,
            category: 'Кроссоверы',
            price: 3990000,
            images: [
                '/img/catalog/jp/Toyota-Harrier-new/1.jpg',
                '/img/catalog/jp/Toyota-Harrier-new/2.jpg',
                '/img/catalog/jp/Toyota-Harrier-new/13.jpg',
                '/img/catalog/jp/Toyota-Harrier-new/14.jpg',
                '/img/catalog/jp/Toyota-Harrier-new/10.jpg',
                '/img/catalog/jp/Toyota-Harrier-new/11.jpg',
                '/img/catalog/jp/Toyota-Harrier-new/12.jpg',
                '/img/catalog/jp/Toyota-Harrier-new/5.jpg',
                '/img/catalog/jp/Toyota-Harrier-new/3.jpg',
                '/img/catalog/jp/Toyota-Harrier-new/4.jpg',
                '/img/catalog/jp/Toyota-Harrier-new/6.jpg',
                '/img/catalog/jp/Toyota-Harrier-new/7.jpg',
                '/img/catalog/jp/Toyota-Harrier-new/8.jpg',
                '/img/catalog/jp/Toyota-Harrier-new/9.jpg',
                '/img/catalog/jp/Toyota-Harrier-new/15.jpg',
                '/img/catalog/jp/Toyota-Harrier-new/16.jpg',
            ],
            specs: {
                mileage: 0,
                engineVolume: 2.5,
                fuelType: 'Гибрид',
                horsePower: 178,
                transmission: 'Вариатор',
                driveType: 'Передний',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '45',
            brand: 'Toyota',
            model: 'RAV-4 Fashion',
            year: 2020,
            category: 'Кроссоверы',
            price: 2950000,
            images: [
                '/img/catalog/jp/Rav4-2020/1.jpg',
                '/img/catalog/jp/Rav4-2020/2.jpg',
                '/img/catalog/jp/Rav4-2020/3.jpg',
                '/img/catalog/jp/Rav4-2020/4.jpg',
                '/img/catalog/jp/Rav4-2020/5.jpg',
                '/img/catalog/jp/Rav4-2020/6.jpg',
                '/img/catalog/jp/Rav4-2020/7.jpg',
                '/img/catalog/jp/Rav4-2020/8.jpg',
                '/img/catalog/jp/Rav4-2020/9.jpg',
                '/img/catalog/jp/Rav4-2020/10.jpg',
                '/img/catalog/jp/Rav4-2020/11.jpg',
                '/img/catalog/jp/Rav4-2020/12.jpg',
            ],
            specs: {
                mileage: 37000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 171,
                transmission: 'Вариатор',
                driveType: '4WD',
                color: 'Белый',
                generation: '5 поколение',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '46',
            brand: 'Toyota',
            model: 'Wildlander',
            year: 2021,
            category: 'Кроссоверы',
            price: 2716000,
            images: [
                '/img/catalog/jp/Toyota-Wildlander/1.jpg',
                '/img/catalog/jp/Toyota-Wildlander/2.jpg',
                '/img/catalog/jp/Toyota-Wildlander/3.jpg',
                '/img/catalog/jp/Toyota-Wildlander/4.jpg',
                '/img/catalog/jp/Toyota-Wildlander/5.jpg',
                '/img/catalog/jp/Toyota-Wildlander/6.jpg',
                '/img/catalog/jp/Toyota-Wildlander/7.jpg',
                '/img/catalog/jp/Toyota-Wildlander/8.jpg',
                '/img/catalog/jp/Toyota-Wildlander/9.jpg',
                '/img/catalog/jp/Toyota-Wildlander/10.jpg',
                '/img/catalog/jp/Toyota-Wildlander/11.jpg',
                '/img/catalog/jp/Toyota-Wildlander/12.jpg',
                '/img/catalog/jp/Toyota-Wildlander/13.jpg',
                '/img/catalog/jp/Toyota-Wildlander/14.jpg',
                '/img/catalog/jp/Toyota-Wildlander/15.jpg',
                '/img/catalog/jp/Toyota-Wildlander/16.jpg',
                '/img/catalog/jp/Toyota-Wildlander/17.jpg',
                '/img/catalog/jp/Toyota-Wildlander/18.jpg',
            ],
            specs: {
                mileage: 31000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 171,
                transmission: 'Вариатор',
                driveType: '4WD',
                color: 'Белый',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
    ],
    korea: [
        {
            id: '44',
            brand: 'Hyundai',
            model: 'Elantra',
            year: 2021,
            category: 'Седаны',
            price: 2140000,
            images: [
                '/img/catalog/korea/Hyundai-Elantra/1.jpg',
                '/img/catalog/korea/Hyundai-Elantra/2.jpg',
                '/img/catalog/korea/Hyundai-Elantra/3.jpg',
                '/img/catalog/korea/Hyundai-Elantra/4.jpg',
                '/img/catalog/korea/Hyundai-Elantra/5.jpg',
                '/img/catalog/korea/Hyundai-Elantra/6.jpg',
                '/img/catalog/korea/Hyundai-Elantra/7.jpg',
                '/img/catalog/korea/Hyundai-Elantra/8.jpg',
                '/img/catalog/korea/Hyundai-Elantra/9.jpg',
                '/img/catalog/korea/Hyundai-Elantra/10.jpg',
                '/img/catalog/korea/Hyundai-Elantra/11.jpg',
                '/img/catalog/korea/Hyundai-Elantra/12.jpg',
                '/img/catalog/korea/Hyundai-Elantra/13.jpg',
                '/img/catalog/korea/Hyundai-Elantra/14.jpg',
                '/img/catalog/korea/Hyundai-Elantra/15.jpg',
                '/img/catalog/korea/Hyundai-Elantra/16.jpg',
                '/img/catalog/korea/Hyundai-Elantra/17.jpg',
            ],
            specs: {
                mileage: 22000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 115,
                transmission: 'Вариатор',
                driveType: 'Передний',
                color: 'Синий',
            },

            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '45',
            brand: 'Hyundai',
            model: 'Tucson',
            year: 2021,
            category: 'Кроссоверы',
            price: 1930000,
            images: [
                '/img/catalog/korea/Hyundai-Tucson/1.jpg',
                '/img/catalog/korea/Hyundai-Tucson/2.jpg',
                '/img/catalog/korea/Hyundai-Tucson/3.jpg',
                '/img/catalog/korea/Hyundai-Tucson/4.jpg',
                '/img/catalog/korea/Hyundai-Tucson/5.jpg',
                '/img/catalog/korea/Hyundai-Tucson/6.jpg',
                '/img/catalog/korea/Hyundai-Tucson/7.jpg',
                '/img/catalog/korea/Hyundai-Tucson/8.jpg',
            ],
            specs: {
                mileage: 31000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 200,
                transmission: 'Робот',
                driveType: 'Передний',
                color: 'Серый',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '46',
            brand: 'KIA',
            model: 'K5',
            year: 2021,
            category: 'Седаны',
            price: 2190000,
            images: [
                '/img/catalog/korea/KIA-K5/1.jpg',
                '/img/catalog/korea/KIA-K5/2.jpg',
                '/img/catalog/korea/KIA-K5/3.jpg',
                '/img/catalog/korea/KIA-K5/10.jpg',
                '/img/catalog/korea/KIA-K5/11.jpg',
                '/img/catalog/korea/KIA-K5/12.jpg',
                '/img/catalog/korea/KIA-K5/4.jpg',
                '/img/catalog/korea/KIA-K5/5.jpg',
                '/img/catalog/korea/KIA-K5/6.jpg',
                '/img/catalog/korea/KIA-K5/7.jpg',
                '/img/catalog/korea/KIA-K5/8.jpg',
                '/img/catalog/korea/KIA-K5/9.jpg',
            ],
            specs: {
                mileage: 22000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 240,
                transmission: 'АКПП',
                driveType: 'Передний',
                color: 'Серый',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
    ],
    europe: [
        {
            id: '20',
            brand: 'BMW',
            model: 'X1',
            year: 2021,
            category: 'Кроссоверы',
            price: 2332500,
            images: [
                '/img/catalog/eu/BMW-X1/1.jpg',
                '/img/catalog/eu/BMW-X1/2.jpg',
                '/img/catalog/eu/BMW-X1/3.jpg',
                '/img/catalog/eu/BMW-X1/4.jpg',
                '/img/catalog/eu/BMW-X1/5.jpg',
                '/img/catalog/eu/BMW-X1/6.jpg',
                '/img/catalog/eu/BMW-X1/7.jpg',
                '/img/catalog/eu/BMW-X1/8.jpg',
                '/img/catalog/eu/BMW-X1/9.jpg',
                '/img/catalog/eu/BMW-X1/10.jpg',
                '/img/catalog/eu/BMW-X1/11.jpg',
                '/img/catalog/eu/BMW-X1/12.jpg',
                '/img/catalog/eu/BMW-X1/23.jpg',
                '/img/catalog/eu/BMW-X1/13.jpg',
                '/img/catalog/eu/BMW-X1/18.jpg',
                '/img/catalog/eu/BMW-X1/14.jpg',
                '/img/catalog/eu/BMW-X1/15.jpg',
                '/img/catalog/eu/BMW-X1/16.jpg',
                '/img/catalog/eu/BMW-X1/17.jpg',
                '/img/catalog/eu/BMW-X1/19.jpg',
                '/img/catalog/eu/BMW-X1/20.jpg',
                '/img/catalog/eu/BMW-X1/21.jpg',
                '/img/catalog/eu/BMW-X1/22.jpg',
                '/img/catalog/eu/BMW-X1/24.jpg',
                '/img/catalog/eu/BMW-X1/25.jpg',
            ],
            specs: {
                mileage: 30000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 140,
                transmission: 'АКПП-робот (7 ступеней)',
                driveType: 'Передний',
                color: '',
                generation: 'sDrive 20Li SAT Exclusive',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '21',
            brand: 'Mercedes-Benz',
            model: 'C-Class',
            year: 2021,
            category: 'Седаны',
            price: 2950000,
            images: [
                '/img/catalog/eu/Mercedes-Benz-C-Class/1.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/2.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/3.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/4.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/5.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/6.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/7.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/21.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/22.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/23.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/24.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/13.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/8.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/9.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/10.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/11.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/12.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/14.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/15.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/16.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/17.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/18.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/19.jpg',
                '/img/catalog/eu/Mercedes-Benz-C-Class/20.jpg',
            ],
            specs: {
                mileage: 45000,
                engineVolume: 1.5,
                fuelType: 'Бензин',
                horsePower: 156,
                transmission: 'АКПП автомат',
                driveType: 'Задний',
                color: '',
                generation: '200L Fashion Sport',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '22',
            brand: 'Mercedes-Benz',
            model: 'GLB',
            year: 2021,
            category: 'Кроссоверы',
            price: 3350000,
            images: [
                '/img/catalog/eu/Mercedes-Benz-GLB/1.jpg',
                '/img/catalog/eu/Mercedes-Benz-GLB/2.jpg',
                '/img/catalog/eu/Mercedes-Benz-GLB/3.jpg',
                '/img/catalog/eu/Mercedes-Benz-GLB/7.jpg',
                '/img/catalog/eu/Mercedes-Benz-GLB/8.jpg',
                '/img/catalog/eu/Mercedes-Benz-GLB/9.jpg',
                '/img/catalog/eu/Mercedes-Benz-GLB/4.jpg',
                '/img/catalog/eu/Mercedes-Benz-GLB/5.jpg',
                '/img/catalog/eu/Mercedes-Benz-GLB/6.jpg',
                '/img/catalog/eu/Mercedes-Benz-GLB/10.jpg',
            ],
            specs: {
                mileage: 31000,
                engineVolume: 1.3,
                fuelType: 'Бензин',
                horsePower: 163,
                transmission: 'АКПП робот',
                driveType: 'Передний',
                color: '',
                generation: '200',
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '23',
            brand: 'Volkswagen',
            model: 'Golf',
            year: 2020,
            category: 'Хэтчбеки',
            price: 1950000,
            images: [
                '/img/catalog/eu/WV-GOLF/1.jpg',
                '/img/catalog/eu/WV-GOLF/2.jpg',
                '/img/catalog/eu/WV-GOLF/3.jpg',
                '/img/catalog/eu/WV-GOLF/4.jpg',
                '/img/catalog/eu/WV-GOLF/5.jpg',
                '/img/catalog/eu/WV-GOLF/6.jpg',
                '/img/catalog/eu/WV-GOLF/7.jpg',
                '/img/catalog/eu/WV-GOLF/19.jpg',
                '/img/catalog/eu/WV-GOLF/8.jpg',
                '/img/catalog/eu/WV-GOLF/9.jpg',
                '/img/catalog/eu/WV-GOLF/10.jpg',
                '/img/catalog/eu/WV-GOLF/11.jpg',
                '/img/catalog/eu/WV-GOLF/12.jpg',
                '/img/catalog/eu/WV-GOLF/13.jpg',
                '/img/catalog/eu/WV-GOLF/14.jpg',
                '/img/catalog/eu/WV-GOLF/15.jpg',
                '/img/catalog/eu/WV-GOLF/16.jpg',
                '/img/catalog/eu/WV-GOLF/17.jpg',
                '/img/catalog/eu/WV-GOLF/18.jpg',
                '/img/catalog/eu/WV-GOLF/20.jpg',
            ],
            specs: {
                mileage: 60000,
                engineVolume: 1.4,
                fuelType: 'Бензин',
                horsePower: 150,
                transmission: 'АКПП робот',
                driveType: 'Передний',
                color: '',
                generation: '280 TSI DSG PRO',
                features: [
                    'Подогрев руля',
                    'Люк',
                    'Обогрев зеркал',
                    'Беспроводная зарядка',
                ],
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '24',
            brand: 'Volkswagen',
            model: 'TiguanL',
            year: 2021,
            category: 'Кроссоверы',
            price: 3235000,
            images: [
                '/img/catalog/eu/Volkswagen-TiguanL/1.jpg',
                '/img/catalog/eu/Volkswagen-TiguanL/2.jpg',
                '/img/catalog/eu/Volkswagen-TiguanL/3.jpg',
                '/img/catalog/eu/Volkswagen-TiguanL/4.jpg',
                '/img/catalog/eu/Volkswagen-TiguanL/5.jpg',
                '/img/catalog/eu/Volkswagen-TiguanL/12.jpg',
                '/img/catalog/eu/Volkswagen-TiguanL/6.jpg',
                '/img/catalog/eu/Volkswagen-TiguanL/7.jpg',
                '/img/catalog/eu/Volkswagen-TiguanL/8.jpg',
                '/img/catalog/eu/Volkswagen-TiguanL/9.jpg',
                '/img/catalog/eu/Volkswagen-TiguanL/10.jpg',
                '/img/catalog/eu/Volkswagen-TiguanL/11.jpg',
                '/img/catalog/eu/Volkswagen-TiguanL/13.jpg',
                '/img/catalog/eu/Volkswagen-TiguanL/14.jpg',
            ],
            specs: {
                mileage: 35000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 220,
                transmission: 'АКПП робот',
                driveType: '4WD',
                color: '',
                generation: '1 поколение, рестайлинг',
                features: ['2.0 380 TSI DSG R-Line Flagship'],
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            id: '25',
            brand: 'Skoda',
            model: 'Kamiq',
            year: 2022,
            category: 'Седаны',
            price: 1335000,
            images: [
                '/img/catalog/eu/Skoda-Kamiq/1.jpg',
                '/img/catalog/eu/Skoda-Kamiq/2.jpg',
                '/img/catalog/eu/Skoda-Kamiq/3.jpg',
                '/img/catalog/eu/Skoda-Kamiq/4.jpg',
                '/img/catalog/eu/Skoda-Kamiq/5.jpg',
                '/img/catalog/eu/Skoda-Kamiq/6.jpg',
                '/img/catalog/eu/Skoda-Kamiq/7.jpg',
                '/img/catalog/eu/Skoda-Kamiq/8.jpg',
                '/img/catalog/eu/Skoda-Kamiq/9.jpg',
                '/img/catalog/eu/Skoda-Kamiq/10.jpg',
                '/img/catalog/eu/Skoda-Kamiq/11.jpg',
                '/img/catalog/eu/Skoda-Kamiq/12.jpg',
                '/img/catalog/eu/Skoda-Kamiq/13.jpg',
                '/img/catalog/eu/Skoda-Kamiq/14.jpg',
                '/img/catalog/eu/Skoda-Kamiq/15.jpg',
                '/img/catalog/eu/Skoda-Kamiq/16.jpg',
                '/img/catalog/eu/Skoda-Kamiq/17.jpg',
                '/img/catalog/eu/Skoda-Kamiq/18.jpg',
                '/img/catalog/eu/Skoda-Kamiq/19.jpg',
                '/img/catalog/eu/Skoda-Kamiq/20.jpg',
                '/img/catalog/eu/Skoda-Kamiq/21.jpg',
                '/img/catalog/eu/Skoda-Kamiq/22.jpg',
                '/img/catalog/eu/Skoda-Kamiq/23.jpg',
                '/img/catalog/eu/Skoda-Kamiq/24.jpg',
                '/img/catalog/eu/Skoda-Kamiq/25.jpg',
            ],
            specs: {
                mileage: 12000,
                engineVolume: 2.0,
                fuelType: 'Бензин',
                horsePower: 109,
                transmission: 'АКПП',
                driveType: 'Передний',
                color: 'Белый',
                generation: '1 поколение, рестайлинг',
                features: ['2.0 380 TSI DSG R-Line Flagship'],
            },
            available: false,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
    ],
}
