version: '3.8'

services:
    bot:
        build: .
        container_name: tg_am_bot
        volumes:
            - .:/app
            - ./data:/app/data
        env_file:
            - .env
        restart: unless-stopped
